const GET_BLOG_ARTICLES = "GET_BLOG_ARTICLES";
const CREATE_BLOG_ARTICLE = "CREATE_BLOG_ARTICLE";
const DELETE_BLOG_ARTICLE = "DELETE_BLOG_ARTICLE";
const SET_CURRENT_ARTICLE = "SET_CURRENT_ARTICLE";
const CLEAR_CURRENT_ARTICLE = "CLEAR_CURRENT_ARTICLE";
const EDIT_BLOG_ARTICLE = "EDIT_BLOG_ARTICLE";
const FINISH_EDIT_BLOG_ARTICLE = "FINISH_EDIT_BLOG_ARTICLE";
const UPDATE_BLOG_ARTICLE = "UPDATE_BLOG_ARTICLE";
const UPDATE_EDITOR_STATE = "UPDATE_EDITOR_STATE";

export default {
  GET_BLOG_ARTICLES,
  CREATE_BLOG_ARTICLE,
  DELETE_BLOG_ARTICLE,
  SET_CURRENT_ARTICLE,
  CLEAR_CURRENT_ARTICLE,
  EDIT_BLOG_ARTICLE,
  FINISH_EDIT_BLOG_ARTICLE,
  UPDATE_BLOG_ARTICLE,
  UPDATE_EDITOR_STATE
};
